# Generated by Django 3.1.6 on 2021-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modality', models.CharField(blank=True, choices=[('RACES', 'Races'), ('FIGHT', 'Fight'), ('VOLLEY', 'Volley'), ('FOOTBALL', 'Football'), ('SOCCER', 'Soccer')], max_length=100)),
                ('bet_value', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
