# Generated by Django 3.1.6 on 2021-02-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='modality',
            field=models.CharField(blank=True, choices=[('FIGHT', 'Fight'), ('VOLLEY', 'Volley'), ('RACES', 'Races'), ('FOOTBALL', 'Football'), ('SOCCER', 'Soccer')], max_length=100),
        ),
    ]
