# Generated by Django 3.1.6 on 2021-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'masculino'), ('FEMININO', 'feminino'), ('OUTROS', 'outros')], max_length=20),
        ),
    ]
