# Generated by Django 3.1.6 on 2021-02-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('BEVERAGE', 'Beverage'), ('ENTERTAINMENT', 'Entertainment'), ('FOOD', 'Food')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, max_length=50)),
            ],
        ),
    ]
