# Generated by Django 3.1.6 on 2021-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210209_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', 'Food'), ('BEVERAGE', 'Beverage'), ('ENTERTAINMENT', 'Entertainment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
