# Generated by Django 3.1.6 on 2021-02-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210209_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('ENTERTAINMENT', 'Entertainment'), ('FOOD', 'Food'), ('BEVERAGE', 'Beverage')], max_length=100),
        ),
    ]
